export interface University {
  id: number
  name: string
  type: "federal" | "state" | "private"
  state: string
  established?: number
  website?: string
  abbreviation?: string
}

export const universities: University[] = [
  // Federal Universities
  {
    id: 1,
    name: "Abubakar Tafawa Balewa University, Bauchi",
    type: "federal",
    state: "Bauchi",
    established: 1988,
    website: "http://www.atbu.edu.ng/",
    abbreviation: "ATBU",
  },
  {
    id: 2,
    name: "Adeyemi Federal University of Education, Ondo",
    type: "federal",
    state: "Ondo",
    established: 2021,
    website: "https://aceondo.edu.ng/",
  },
  {
    id: 3,
    name: "Admiralty University Ibusa, Delta State",
    type: "federal",
    state: "Delta",
    website: "https://adun.edu.ng",
    abbreviation: "ADMIRALTY",
  },
  {
    id: 4,
    name: "African Aviation and Aerospace University",
    type: "federal",
    state: "Abuja",
    website: "https://aaau.edu.ng/",
    abbreviation: "AAAU",
  },
  {
    id: 5,
    name: "Ahmadu Bello University, Zaria",
    type: "federal",
    state: "Kaduna",
    established: 1962,
    website: "http://www.abu.edu.ng/",
    abbreviation: "ABU",
  },
  {
    id: 6,
    name: "Air Force Institute of Technology, Kaduna",
    type: "federal",
    state: "Kaduna",
    website: "https://afit.edu.ng",
    abbreviation: "AFIT",
  },
  {
    id: 7,
    name: "Alex Ekwueme University, Ndufu-Alike, Ebonyi State",
    type: "federal",
    state: "Ebonyi",
    website: "http://www.funai.edu.ng",
    abbreviation: "AE-FUNAI",
  },
  {
    id: 8,
    name: "Alvan Ikoku Federal University of Education, Owerri, Imo State",
    type: "federal",
    state: "Imo",
    website: "https://www.alvanikoku.edu.ng/",
  },
  {
    id: 9,
    name: "Bayero University, Kano",
    type: "federal",
    state: "Kano",
    established: 1975,
    website: "http://www.buk.edu.ng/",
    abbreviation: "BUK",
  },
  {
    id: 10,
    name: "David Nweze Umahi Federal University of Medical Sciences, Uburu",
    type: "federal",
    state: "Ebonyi",
    website: "https://kdums.edu.ng/",
    abbreviation: "DUFUHS",
  },
  {
    id: 11,
    name: "Federal University Gashua, Yobe",
    type: "federal",
    state: "Yobe",
    website: "http://www.fugashua.edu.ng/",
    abbreviation: "FUGASHUA",
  },
  {
    id: 12,
    name: "Federal University of Agriculture Bassam-Biri, Bayelsa",
    type: "federal",
    state: "Bayelsa",
  },
  {
    id: 13,
    name: "Federal University of Agriculture, Abeokuta",
    type: "federal",
    state: "Ogun",
    established: 1988,
    website: "http://www.unaab.edu.ng/",
    abbreviation: "FUNAAB",
  },
  {
    id: 14,
    name: "Federal University of Agriculture, Mubi",
    type: "federal",
    state: "Adamawa",
  },
  {
    id: 15,
    name: "Federal University of Agriculture, Zuru, Kebbi State",
    type: "federal",
    state: "Kebbi",
    website: "https://fuhsi.edu.ng/",
    abbreviation: "FUAZ",
  },
  {
    id: 16,
    name: "Federal University of Education, Kano",
    type: "federal",
    state: "Kano",
    website: "https://fcekano.edu.ng/",
    abbreviation: "FCEKANO",
  },
  {
    id: 17,
    name: "Federal University of Education, Zaria, Kaduna State",
    type: "federal",
    state: "Kaduna",
    website: "https://fcezaria.edu.ng/",
    abbreviation: "FCEZRIA",
  },
  {
    id: 18,
    name: "Federal University of Health Sciences Kwale, Delta State",
    type: "federal",
    state: "Delta",
  },
  {
    id: 19,
    name: "Federal University of Health Sciences, Azare, Bauchi State",
    type: "federal",
    state: "Bauchi",
    website: "https://fuhsa.edu.ng/",
    abbreviation: "FUHSA",
  },
  {
    id: 20,
    name: "Federal University of Health Sciences, Ila Orangun, Osun State",
    type: "federal",
    state: "Osun",
    website: "https://fuhsi.edu.ng/",
    abbreviation: "FUHSI",
  },
  {
    id: 21,
    name: "Federal University of Health Sciences, Katsina",
    type: "federal",
    state: "Katsina",
  },
  {
    id: 22,
    name: "Federal University of Health Sciences, Otukpo, Benue State",
    type: "federal",
    state: "Benue",
    website: "http://www.fuhso.edu.ng/",
    abbreviation: "FUHSO",
  },
  {
    id: 23,
    name: "Federal University of Petroleum Resources, Effurun",
    type: "federal",
    state: "Delta",
    established: 2007,
    website: "http://www.fupre.edu.ng",
    abbreviation: "FUPRE",
  },
  {
    id: 24,
    name: "Federal University of Technology, Akure",
    type: "federal",
    state: "Ondo",
    established: 1981,
    website: "http://www.futa.edu.ng",
    abbreviation: "FUTA",
  },
  {
    id: 25,
    name: "Federal University of Technology, Babura, Jigawa State",
    type: "federal",
    state: "Jigawa",
    website: "https://futb.edu.ng/",
    abbreviation: "FUTB",
  },
  {
    id: 26,
    name: "Federal University of Technology, Ikot Abasi, Akwa Ibom State",
    type: "federal",
    state: "Akwa Ibom",
    website: "https://futia.edu.ng/",
    abbreviation: "FUTIA",
  },
  {
    id: 27,
    name: "Federal University of Technology, Minna",
    type: "federal",
    state: "Niger",
    established: 1983,
    website: "http://www.futminna.edu.ng",
    abbreviation: "FUTMINNA",
  },
  {
    id: 28,
    name: "Federal University of Technology, Owerri",
    type: "federal",
    state: "Imo",
    established: 1980,
    website: "http://www.futo.edu.ng",
    abbreviation: "FUTO",
  },
  {
    id: 29,
    name: "Federal University of Transportation Daura, Katsina",
    type: "federal",
    state: "Katsina",
    website: "https://www.futd.edu.ng/",
    abbreviation: "FUTD",
  },
  {
    id: 30,
    name: "Federal University, Birnin Kebbi",
    type: "federal",
    state: "Kebbi",
    website: "http://www.fubk.edu.ng",
    abbreviation: "FUBK",
  },
  {
    id: 31,
    name: "Federal University, Dutse, Jigawa State",
    type: "federal",
    state: "Jigawa",
    website: "http://www.fud.edu.ng/",
    abbreviation: "FUD",
  },
  {
    id: 32,
    name: "Federal University, Dutsin-Ma, Katsina",
    type: "federal",
    state: "Katsina",
    website: "http://www.fudutsinma.edu.ng",
    abbreviation: "FUDMA",
  },
  {
    id: 33,
    name: "Federal University, Gusau Zamfara",
    type: "federal",
    state: "Zamfara",
    website: "http://www.fugusau.edu.ng",
    abbreviation: "FUGUS",
  },
  {
    id: 34,
    name: "Federal University, Kashere, Gombe State",
    type: "federal",
    state: "Gombe",
    website: "http://www.fukashere.edu.ng",
    abbreviation: "FUKASHERE",
  },
  {
    id: 35,
    name: "Federal University, Lafia, Nasarawa State",
    type: "federal",
    state: "Nasarawa",
    website: "http://www.fulafia.edu.ng",
    abbreviation: "FULAFIA",
  },
  {
    id: 36,
    name: "Federal University, Lokoja, Kogi State",
    type: "federal",
    state: "Kogi",
    website: "http://www.fulokoja.edu.ng",
    abbreviation: "FULOKOJA",
  },
  {
    id: 37,
    name: "Federal University, Otuoke, Bayelsa",
    type: "federal",
    state: "Bayelsa",
    website: "http://www.fuotuoke.edu.ng/",
    abbreviation: "FUOTUOKE",
  },
  {
    id: 38,
    name: "Federal University, Oye-Ekiti, Ekiti State",
    type: "federal",
    state: "Ekiti",
    website: "http://www.fuoye.edu.ng/",
    abbreviation: "FUOYE",
  },
  {
    id: 39,
    name: "Federal University, Wukari, Taraba State",
    type: "federal",
    state: "Taraba",
    website: "http://www.fuwukari.edu.ng/",
    abbreviation: "FUWUKARI",
  },
  {
    id: 40,
    name: "Michael Okpara University of Agricultural Umudike",
    type: "federal",
    state: "Abia",
    established: 1992,
    website: "http://www.mouau.edu.ng",
    abbreviation: "MOUAU",
  },
  {
    id: 41,
    name: "Modibbo Adama University of Technology, Yola",
    type: "federal",
    state: "Adamawa",
    established: 1981,
    website: "http://www.mautech.edu.ng",
    abbreviation: "MAUTECH",
  },
  {
    id: 42,
    name: "National Institute for Construction Technology and Management, Uromi",
    type: "federal",
    state: "Edo",
    website: "https://nict.edu.ng/",
    abbreviation: "NICTM",
  },
  {
    id: 43,
    name: "National Open University of Nigeria, Lagos",
    type: "federal",
    state: "Lagos",
    established: 2002,
    website: "http://www.nou.edu.ng",
    abbreviation: "NOUN",
  },
  {
    id: 44,
    name: "National University of Science and Technology, Abuja",
    type: "federal",
    state: "Abuja",
    website: "https://www.aust.edu.ng/",
    abbreviation: "AUST",
  },
  {
    id: 45,
    name: "Nigeria Police Academy Wudil",
    type: "federal",
    state: "Kano",
    website: "http://polac.edu.ng/",
    abbreviation: "POLAC",
  },
  {
    id: 46,
    name: "Nigerian Army University Biu",
    type: "federal",
    state: "Borno",
    website: "https://naub.edu.ng/",
    abbreviation: "NAUB",
  },
  {
    id: 47,
    name: "Nigerian Defence Academy Kaduna",
    type: "federal",
    state: "Kaduna",
    established: 1985,
    website: "http://www.nda.edu.ng",
    abbreviation: "NDA",
  },
  {
    id: 48,
    name: "Nigerian Maritime University Okerenkoko, Delta State",
    type: "federal",
    state: "Delta",
    abbreviation: "NMU",
  },
  {
    id: 49,
    name: "Nnamdi Azikiwe University, Awka",
    type: "federal",
    state: "Anambra",
    established: 1991,
    website: "http://www.unizik.edu.ng",
    abbreviation: "UNIZIK",
  },
  {
    id: 50,
    name: "Obafemi Awolowo University, Ile-Ife",
    type: "federal",
    state: "Osun",
    established: 1962,
    website: "http://www.oauife.edu.ng",
    abbreviation: "OAU",
  },
  {
    id: 51,
    name: "University of Abuja, Gwagwalada",
    type: "federal",
    state: "Abuja",
    established: 1988,
    website: "http://www.uniabuja.edu.ng",
    abbreviation: "UNIBUJA",
  },
  {
    id: 52,
    name: "University of Agriculture, Makurdi",
    type: "federal",
    state: "Benue",
    established: 1988,
    website: "http://www.uam.edu.ng",
    abbreviation: "FUAM",
  },
  {
    id: 53,
    name: "University of Benin",
    type: "federal",
    state: "Edo",
    established: 1970,
    website: "http://www.uniben.edu.ng",
    abbreviation: "UNIBEN",
  },
  {
    id: 54,
    name: "University of Calabar",
    type: "federal",
    state: "Cross River",
    established: 1975,
    website: "http://www.unical.edu.ng",
    abbreviation: "UNICAL",
  },
  {
    id: 55,
    name: "University of Ibadan",
    type: "federal",
    state: "Oyo",
    established: 1948,
    website: "http://www.ui.edu.ng",
    abbreviation: "UI",
  },
  {
    id: 56,
    name: "University of Ilorin",
    type: "federal",
    state: "Kwara",
    established: 1975,
    website: "http://www.unilorin.edu.ng",
    abbreviation: "UNILORIN",
  },
  {
    id: 57,
    name: "University of Jos",
    type: "federal",
    state: "Plateau",
    established: 1975,
    website: "http://www.unijos.edu.ng",
    abbreviation: "UNIJOS",
  },
  {
    id: 58,
    name: "University of Lagos",
    type: "federal",
    state: "Lagos",
    established: 1962,
    website: "http://www.unilag.edu.ng",
    abbreviation: "UNILAG",
  },
  {
    id: 59,
    name: "University of Maiduguri",
    type: "federal",
    state: "Borno",
    established: 1975,
    website: "http://www.unimaid.edu.ng",
    abbreviation: "UNIMAID",
  },
  {
    id: 60,
    name: "University of Nigeria, Nsukka",
    type: "federal",
    state: "Enugu",
    established: 1960,
    website: "http://www.unn.edu.ng",
    abbreviation: "UNN",
  },
  {
    id: 61,
    name: "University of Port-Harcourt",
    type: "federal",
    state: "Rivers",
    established: 1975,
    website: "http://www.uniport.edu.ng",
    abbreviation: "UNIPORT",
  },
  {
    id: 62,
    name: "University of Uyo",
    type: "federal",
    state: "Akwa Ibom",
    established: 1991,
    website: "http://www.uniuyo.edu.ng",
    abbreviation: "UNIUYO",
  },
  {
    id: 63,
    name: "Usumanu Danfodiyo University",
    type: "federal",
    state: "Sokoto",
    established: 1975,
    website: "http://www.udusok.edu.ng",
    abbreviation: "UDUSOK",
  },

  // State Universities
  {
    id: 64,
    name: "AbdulKadir Kure University, Minna Niger State",
    type: "state",
    state: "Niger",
    website: "https://akum.edu.ng/",
  },
  {
    id: 65,
    name: "Abia State University, Uturu",
    type: "state",
    state: "Abia",
    established: 1981,
    website: "https://abiastateuniversity.edu.ng",
  },
  {
    id: 66,
    name: "Adamawa State University Mubi",
    type: "state",
    state: "Adamawa",
    website: "https://www.adsu.edu.ng",
  },
  {
    id: 67,
    name: "Adekunle Ajasin University, Akungba",
    type: "state",
    state: "Ondo",
    established: 1999,
    website: "https://www.aaua.edu.ng",
  },
  {
    id: 68,
    name: "Akwa Ibom State University, Ikot Akpaden",
    type: "state",
    state: "Akwa Ibom",
    website: "https://www.aksu.edu.ng",
  },
  {
    id: 69,
    name: "Ambrose Alli University, Ekpoma",
    type: "state",
    state: "Edo",
    established: 1981,
    website: "https://www.aauekpoma.edu.ng",
  },
  {
    id: 70,
    name: "Bamidele Olumilua University of Science and Technology Ikere, Ekiti State",
    type: "state",
    state: "Ekiti",
    website: "https://bouesti.edu.ng/",
  },
  {
    id: 71,
    name: "Bauchi State University, Gadau",
    type: "state",
    state: "Bauchi",
    website: "https://www.basug.edu.ng",
  },
  {
    id: 72,
    name: "Bayelsa Medical University",
    type: "state",
    state: "Bayelsa",
    website: "https://bmu.edu.ng/",
  },
  {
    id: 73,
    name: "Benue State University, Makurdi",
    type: "state",
    state: "Benue",
    established: 1992,
    website: "https://www.bsum.edu.ng",
  },
  {
    id: 74,
    name: "Bornu State University, Maiduguri",
    type: "state",
    state: "Borno",
    website: "https://www.bosu.edu.ng/",
  },
  {
    id: 75,
    name: "Chukwuemeka Odumegwu Ojukwu University, Uli",
    type: "state",
    state: "Anambra",
    established: 2000,
    website: "https://coou.edu.ng/",
  },
  {
    id: 76,
    name: "Confluence University of Science and Technology Osara, Kogi",
    type: "state",
    state: "Kogi",
    website: "https://custech.edu.ng/",
  },
  {
    id: 77,
    name: "University of Cross River State (UNICROSS), Ekpo Abasi St, Calabar",
    type: "state",
    state: "Cross River",
    website: "https://unicross.edu.ng",
    abbreviation: "UNICROSS",
  },
  {
    id: 78,
    name: "Delta State University Abraka",
    type: "state",
    state: "Delta",
    established: 1992,
    website: "https://www.delsu.edu.ng",
  },
  {
    id: 79,
    name: "Delta University of Science and Technology, Ozoro",
    type: "state",
    state: "Delta",
    website: "https://dsust.edu.ng/",
  },
  {
    id: 80,
    name: "Dennis Osadebe University, Asaba",
    type: "state",
    state: "Delta",
    website: "https://www.dou.edu.ng/",
  },
  {
    id: 81,
    name: "Ebonyi State University, Abakaliki",
    type: "state",
    state: "Ebonyi",
    established: 1999,
    website: "https://www.ebsu.edu.ng",
  },
  {
    id: 82,
    name: "Edo State University Uzairue",
    type: "state",
    state: "Edo",
    website: "https://www.edouniversity.edu.ng/",
  },
  {
    id: 83,
    name: "Ekiti State University",
    type: "state",
    state: "Ekiti",
    established: 1982,
    website: "https://www.eksu.edu.ng",
  },
  {
    id: 84,
    name: "Emanuel Alayande University of Education Oyo",
    type: "state",
    state: "Oyo",
    website: "https://eauedoyo.edu.ng/",
  },
  {
    id: 85,
    name: "Enugu State University of Science and Technology, Enugu",
    type: "state",
    state: "Enugu",
    established: 1980,
    website: "https://www.esut.edu.ng",
  },
  {
    id: 86,
    name: "First Technical University Ibadan",
    type: "state",
    state: "Oyo",
    website: "https://tech-u.edu.ng/",
  },
  {
    id: 87,
    name: "Gombe State University, Gombe",
    type: "state",
    state: "Gombe",
    website: "https://www.gsu.edu.ng",
  },
  {
    id: 88,
    name: "Gombe State University of Science and Technology",
    type: "state",
    state: "Gombe",
    website: "https://gsu.edu.ng/",
  },
  {
    id: 89,
    name: "Ibrahim Badamasi Babangida University, Lapai",
    type: "state",
    state: "Niger",
    established: 2005,
    website: "https://www.ibbu.edu.ng",
  },
  {
    id: 90,
    name: "Ignatius Ajuru University of Education, Rumuolumeni",
    type: "state",
    state: "Rivers",
    established: 1971,
    website: "https://www.iaue.edu.ng",
  },
  {
    id: 91,
    name: "Imo State University, Owerri",
    type: "state",
    state: "Imo",
    established: 1981,
    website: "https://www.imsu.edu.ng",
  },
  {
    id: 92,
    name: "Kaduna State University, Kaduna",
    type: "state",
    state: "Kaduna",
    established: 2004,
    website: "https://www.kasu.edu.ng",
  },
  {
    id: 93,
    name: "Aliko Dangote University of Science and Technology (ADUST) Wudil, Kano",
    type: "state",
    state: "Kano",
    website: "http://kustwudil.edu.ng",
    abbreviation: "ADUST",
  },
  {
    id: 94,
    name: "Kebbi State University of Science and Technology, Aliero",
    type: "state",
    state: "Kebbi",
    website: "https://www.ksusta.edu.ng",
  },
  {
    id: 95,
    name: "Kingsley Ozumba Mbadiwe University Ogboko, Imo State",
    type: "state",
    state: "Imo",
    website: "https://www.komu.edu.ng/",
  },
  {
    id: 96,
    name: "Kogi State University, Kabba",
    type: "state",
    state: "Kogi",
    website: "https://ksukabba.edu.ng/",
  },
  {
    id: 97,
    name: "Kwara State University, Ilorin",
    type: "state",
    state: "Kwara",
    established: 2009,
    website: "https://www.kwasu.edu.ng",
  },
  {
    id: 98,
    name: "Ladoke Akintola University of Technology, Ogbomoso",
    type: "state",
    state: "Oyo",
    established: 1990,
    website: "https://www.lautech.edu.ng",
  },
  {
    id: 99,
    name: "Lagos State University of Education, Ijanikin",
    type: "state",
    state: "Lagos",
    website: "https://lasued.edu.ng/",
  },
  {
    id: 100,
    name: "Lagos State University of Science and Technology Ikorodu",
    type: "state",
    state: "Lagos",
    website: "https://lasustech.edu.ng/",
  },
  {
    id: 101,
    name: "Lagos State University, Ojo",
    type: "state",
    state: "Lagos",
    established: 1983,
    website: "https://www.lasu.edu.ng",
  },
  {
    id: 102,
    name: "Moshood Abiola University of Science and Technology Abeokuta",
    type: "state",
    state: "Ogun",
  },
  {
    id: 103,
    name: "Nasarawa State University Keffi",
    type: "state",
    state: "Nasarawa",
    established: 2002,
    website: "https://www.nsuk.edu.ng",
  },
  {
    id: 104,
    name: "Niger Delta University Yenagoa",
    type: "state",
    state: "Bayelsa",
    established: 2000,
    website: "https://www.ndu.edu.ng",
  },
  {
    id: 105,
    name: "Olabisi Onabanjo University, Ago Iwoye",
    type: "state",
    state: "Ogun",
    established: 1982,
    website: "https://www.oouagoiwoye.edu.ng",
  },
  {
    id: 106,
    name: "Ondo State University of Medical Sciences",
    type: "state",
    state: "Ondo",
    website: "https://www.unimed.edu.ng",
  },
  {
    id: 107,
    name: "Olusegun Agagu University of Science and Technology, Okitipupa, Ondo",
    type: "state",
    state: "Ondo",
    website: "https://oaustech.edu.ng/",
  },
  {
    id: 108,
    name: "Osun State University Osogbo",
    type: "state",
    state: "Osun",
    established: 2006,
    website: "https://www.uniosun.edu.ng",
  },
  {
    id: 109,
    name: "Plateau State University Bokkos",
    type: "state",
    state: "Plateau",
    website: "https://www.plasu.edu.ng",
  },
  {
    id: 110,
    name: "Prince Abubakar Audu University Anyigba",
    type: "state",
    state: "Kogi",
    website: "https://paau.edu.ng",
  },
  {
    id: 111,
    name: "Rivers State University",
    type: "state",
    state: "Rivers",
    established: 1980,
    website: "https://www.rsu.edu.ng",
  },
  {
    id: 112,
    name: "Sa'adatu Rimi University of Education",
    type: "state",
    state: "Kano",
    website: "https://srcoe.edu.ng/",
  },
  {
    id: 113,
    name: "Shehu Shagari University of Education, Sokoto",
    type: "state",
    state: "Sokoto",
    website: "https://ssues.edu.ng/",
  },
  {
    id: 114,
    name: "Sokoto State University",
    type: "state",
    state: "Sokoto",
    website: "https://www.ssu.edu.ng",
  },
  {
    id: 115,
    name: "State University of Medical and Applied Sciences, Igbo-Eno, Enugu",
    type: "state",
    state: "Enugu",
    website: "https://sumas.edu.ng/",
  },
  {
    id: 116,
    name: "Sule Lamido University, Kafin Hausa, Jigawa",
    type: "state",
    state: "Jigawa",
    website: "https://www.slu.edu.ng",
  },
  {
    id: 117,
    name: "Tai Solarin University of Education Ijebu Ode",
    type: "state",
    state: "Ogun",
    established: 2005,
    website: "https://www.tasued.edu.ng",
  },
  {
    id: 118,
    name: "Taraba State University, Jalingo",
    type: "state",
    state: "Taraba",
    website: "https://www.tsuniversity.edu.ng",
  },
  {
    id: 119,
    name: "Umar Musa Yar' Adua University Katsina",
    type: "state",
    state: "Katsina",
    established: 2006,
    website: "https://www.umyu.edu.ng",
  },
  {
    id: 120,
    name: "University of Africa Toru Orua, Bayelsa State",
    type: "state",
    state: "Bayelsa",
    website: "https://www.uat.edu.ng/",
  },
  {
    id: 121,
    name: "University of Agriculture and Environmental Sciences Umuagwo, Imo State",
    type: "state",
    state: "Imo",
    website: "https://www.uaes.edu.ng/",
  },
  {
    id: 122,
    name: "University of Delta, Agbor",
    type: "state",
    state: "Delta",
    website: "https://unidel.edu.ng/",
  },
  {
    id: 123,
    name: "University of Ilesa, Osun State",
    type: "state",
    state: "Osun",
    website: "https://www.unilesa.edu.ng/",
  },
  {
    id: 124,
    name: "Yobe State University, Damaturu",
    type: "state",
    state: "Yobe",
    established: 2006,
    website: "https://www.ysu.edu.ng",
  },
  {
    id: 125,
    name: "Yusuf Maitama Sule University Kano",
    type: "state",
    state: "Kano",
    website: "https://www.nwu.edu.ng",
  },
  {
    id: 126,
    name: "Zamfara State University",
    type: "state",
    state: "Zamfara",
    website: "https://zamsut.edu.ng/",
  },

  // Private Universities
  {
    id: 127,
    name: "Achievers University, Owo",
    type: "private",
    state: "Ondo",
    established: 2007,
    website: "https://www.achievers.edu.ng",
  },
  {
    id: 128,
    name: "Adeleke University, Ede",
    type: "private",
    state: "Osun",
    established: 2011,
    website: "https://www.adelekeuniversity.edu.ng",
  },
  {
    id: 129,
    name: "Afe Babalola University, Ado-Ekiti - Ekiti State",
    type: "private",
    state: "Ekiti",
    established: 2009,
    website: "https://www.abuad.edu.ng",
  },
  {
    id: 130,
    name: "African University of Economics, FCT, Abuja",
    type: "private",
    state: "Abuja",
    website: "https://africanschoolofeconomics.com/",
  },
  {
    id: 131,
    name: "African University of Science and Technology, Abuja",
    type: "private",
    state: "Abuja",
    established: 2007,
    website: "http://aust.edu.ng/",
  },
  {
    id: 132,
    name: "Ahman Pategi University, Kwara State",
    type: "private",
    state: "Kwara",
    website: "http://www.apu.edu.ng/",
  },
  {
    id: 133,
    name: "Ajayi Crowther University, Ibadan",
    type: "private",
    state: "Oyo",
    established: 2005,
    website: "https://www.acu.edu.ng",
  },
  {
    id: 134,
    name: "Al-Ansar University, Maiduguri, Borno",
    type: "private",
    state: "Borno",
    website: "https://www.aum.edu.ng/",
  },
  {
    id: 135,
    name: "Al-Bayan University, Ankpa, Kogi State",
    type: "private",
    state: "Kogi",
    website: "https://albayanuniversity.edu.ng/",
  },
  {
    id: 136,
    name: "Aletheia University, Ago-Iwoye Ogun State",
    type: "private",
    state: "Ogun",
    website: "https://www.aletheiauniversity.edu.ng/",
  },
  {
    id: 137,
    name: "Al-Hikmah University, Ilorin",
    type: "private",
    state: "Kwara",
    established: 2005,
    website: "https://www.alhikmah.edu.ng",
  },
  {
    id: 138,
    name: "Al-Istiqama University, Sumaila, Kano State",
    type: "private",
    state: "Kano",
    website: "https://www.ausumaila.edu.ng/",
  },
  {
    id: 139,
    name: "Al-Muhibbah Open University, Abuja",
    type: "private",
    state: "Abuja",
    website: "https://aou.edu.ng/",
  },
  {
    id: 140,
    name: "Al-Qalam University, Katsina",
    type: "private",
    state: "Katsina",
    established: 2005,
    website: "https://www.auk.edu.ng",
  },
  {
    id: 141,
    name: "Amadeus University, Amizi, Abia State",
    type: "private",
    state: "Abia",
    website: "https://amadeus.edu.ng/",
  },
  {
    id: 142,
    name: "Amaj University, Kwali, Abuja",
    type: "private",
    state: "Abuja",
  },
  {
    id: 143,
    name: "American University of Nigeria, Yola",
    type: "private",
    state: "Adamawa",
    established: 2005,
    website: "https://www.aun.edu.ng",
  },
  {
    id: 144,
    name: "Anan University, Kwall, Plateau State",
    type: "private",
    state: "Plateau",
    website: "https://www.ananuniversity.edu.ng/",
  },
  {
    id: 145,
    name: "Anchor University Ayobo Lagos State",
    type: "private",
    state: "Lagos",
    website: "https://www.aul.edu.ng/",
  },
  {
    id: 146,
    name: "Arthur Javis University Akpoyubo Cross River State",
    type: "private",
    state: "Cross River",
    website: "https://arthurjarvisuniversity.edu.ng/",
  },
  {
    id: 147,
    name: "Atiba University Oyo",
    type: "private",
    state: "Oyo",
    website: "http://www.atibauniversity.edu.ng/",
  },
  {
    id: 148,
    name: "Augustine University",
    type: "private",
    state: "Lagos",
    established: 2015,
    website: "https://www.augustineuniversity.edu.ng/",
  },
  {
    id: 149,
    name: "Ave Maria University, Piyanko, Nasarawa State",
    type: "private",
    state: "Nasarawa",
    website: "https://www.avemariauniversity.edu.ng/",
  },
  {
    id: 150,
    name: "Azman University, Kano State",
    type: "private",
    state: "Kano",
    website: "https://www.azmanuniversity.edu.ng/",
  },
  {
    id: 151,
    name: "Baba Ahmed University, Kano State",
    type: "private",
    state: "Kano",
  },
  {
    id: 152,
    name: "Babcock University, Ilishan-Remo",
    type: "private",
    state: "Ogun",
    established: 1999,
    website: "https://www.babcock.edu.ng",
  },
  {
    id: 153,
    name: "Baze University",
    type: "private",
    state: "Abuja",
    established: 2011,
    website: "https://www.bazeuniversity.edu.ng",
  },
  {
    id: 154,
    name: "Bells University of Technology, Otta",
    type: "private",
    state: "Ogun",
    established: 2005,
    website: "https://www.bellsuniversity.edu.ng/",
  },
  {
    id: 155,
    name: "Benson Idahosa University, Benin City",
    type: "private",
    state: "Edo",
    established: 2002,
    website: "https://www.biu.edu.ng/",
  },
  {
    id: 156,
    name: "Bingham University, New Karu",
    type: "private",
    state: "Nasarawa",
    established: 2005,
    website: "https://www.binghamuni.edu.ng",
  },
  {
    id: 157,
    name: "Bowen University, Iwo",
    type: "private",
    state: "Osun",
    established: 2001,
    website: "https://www.bowen.edu.ng",
  },
  {
    id: 158,
    name: "British Canadian University, Obufu Cross River State",
    type: "private",
    state: "Cross River",
    website: "https://bcu.edu.ng/",
  },
  {
    id: 159,
    name: "Caleb University, Lagos",
    type: "private",
    state: "Lagos",
    established: 2007,
    website: "https://www.calebuniversity.edu.ng",
  },
  {
    id: 160,
    name: "Canadian University of Nigeria, Abuja",
    type: "private",
    state: "Abuja",
    website: "https://www.cun.edu.ng/",
  },
  {
    id: 161,
    name: "Capital City University, Kano State",
    type: "private",
    state: "Kano",
    website: "https://www.ccuk.edu.ng/",
  },
  {
    id: 162,
    name: "Caritas University, Enugu",
    type: "private",
    state: "Enugu",
    established: 2005,
    website: "https://www.caritasuni.edu.ng/",
  },
  {
    id: 163,
    name: "Chrisland University",
    type: "private",
    state: "Ogun",
    established: 2015,
    website: "https://www.chrislanduniversity.edu.ng",
  },
  {
    id: 164,
    name: "Christopher University Mowe",
    type: "private",
    state: "Ogun",
    website: "https://www.christopheruniversity.edu.ng/",
  },
  {
    id: 165,
    name: "Claretian University of Nigeria, Nekede, Imo State",
    type: "private",
    state: "Imo",
    website: "https://claretianuniversity.edu.ng/",
  },
  {
    id: 166,
    name: "Clifford University Owerrinta Abia State",
    type: "private",
    state: "Abia",
    website: "https://www.clifforduni.edu.ng/",
  },
  {
    id: 167,
    name: "Coal City University Enugu State",
    type: "private",
    state: "Enugu",
    website: "https://www.ccu.edu.ng/",
  },
  {
    id: 168,
    name: "College of Petroleum and Energy Studies, Kaduna State",
    type: "private",
    state: "Kaduna",
  },
  {
    id: 169,
    name: "Cosmopolitan University Abuja",
    type: "private",
    state: "Abuja",
    website: "https://cosmopolitan.edu.ng/",
  },
  {
    id: 170,
    name: "Covenant University Ota",
    type: "private",
    state: "Ogun",
    established: 2002,
    website: "https://www.covenantuniversity.edu.ng/",
  },
  {
    id: 171,
    name: "Crawford University Igbesa",
    type: "private",
    state: "Ogun",
    established: 2005,
    website: "https://www.crawforduniversity.edu.ng",
  },
  {
    id: 172,
    name: "Crescent University",
    type: "private",
    state: "Ogun",
    established: 2005,
    website: "https://www.crescent-university.edu.ng",
  },
  {
    id: 173,
    name: "Dominican University Ibadan Oyo State",
    type: "private",
    state: "Oyo",
    website: "https://www.dui.edu.ng/",
  },
  {
    id: 174,
    name: "Dominion University Ibadan, Oyo State",
    type: "private",
    state: "Oyo",
    website: "https://www.dominionuniversity.edu.ng/",
  },
  {
    id: 175,
    name: "Edusoko University, Bida, Niger State",
    type: "private",
    state: "Niger",
    website: "https://edusokouniversity.edu.ng/",
  },
  {
    id: 176,
    name: "Edwin Clark University, Kaigbodo",
    type: "private",
    state: "Delta",
    established: 2015,
    website: "https://www.edwinclarkuniversity.edu.ng/",
  },
  {
    id: 177,
    name: "Eko University of Medical and Health Sciences Ijanikin, Lagos",
    type: "private",
    state: "Lagos",
    website: "https://ekounimed.edu.ng",
  },
  {
    id: 178,
    name: "El-Amin University, Minna, Niger State",
    type: "private",
    state: "Niger",
    website: "https://www.el-aminuniversity.edu.ng/",
  },
  {
    id: 179,
    name: "Elizade University, Ilara-Mokin",
    type: "private",
    state: "Ondo",
    established: 2012,
    website: "https://www.elizadeuniversity.edu.ng",
  },
  {
    id: 180,
    name: "Elrazi Medical University Yargaya University, Kano State",
    type: "private",
    state: "Kano",
    website: "https://elrazi.edu.ng/",
  },
  {
    id: 181,
    name: "European University of Nigeria, Duboyi, FCT",
    type: "private",
    state: "Abuja",
  },
  {
    id: 182,
    name: "Evangel University, Akaeze",
    type: "private",
    state: "Ebonyi",
    established: 2012,
    website: "https://www.evangeluniversity.edu.ng",
  },
  {
    id: 183,
    name: "Fountain University, Oshogbo",
    type: "private",
    state: "Osun",
    established: 2007,
    website: "https://www.fuo.edu.ng",
  },
  {
    id: 184,
    name: "Franco British International University, Kaduna State",
    type: "private",
    state: "Kaduna",
    website: "https://fbiu.edu.ng/",
  },
  {
    id: 185,
    name: "Gerar University of Medical Science Imope Ijebu, Ogun State",
    type: "private",
    state: "Ogun",
    website: "https://gumed.edu.ng/",
  },
  {
    id: 186,
    name: "Glorious Vision University, Ogwa, Edo State",
    type: "private",
    state: "Edo",
    website: "https://www.sau.edu.ng",
  },
  {
    id: 187,
    name: "Godfrey Okoye University, Ugwuomu-Nike - Enugu State",
    type: "private",
    state: "Enugu",
    established: 2009,
    website: "https://www.gouni.edu.ng",
  },
  {
    id: 188,
    name: "Greenfield University, Kaduna",
    type: "private",
    state: "Kaduna",
    website: "https://www.gfu.edu.ng",
  },
  {
    id: 189,
    name: "Gregory University, Uturu",
    type: "private",
    state: "Abia",
    established: 2012,
    website: "https://www.gregoryuniversity.com",
  },
  {
    id: 190,
    name: "Hallmark University, Ijebi Itele, Ogun",
    type: "private",
    state: "Ogun",
    website: "https://hallmarkuniversity.edu.ng",
  },
  {
    id: 191,
    name: "Havilla University, Nde-Ikom, Cross River State",
    type: "private",
    state: "Cross River",
    website: "https://havillauniversity.edu.ng/",
  },
  {
    id: 192,
    name: "Hensard University, Toru-Orua, Sagbama, Bayelsa State",
    type: "private",
    state: "Bayelsa",
    website: "https://hensarduniversity.edu.ng/",
  },
  {
    id: 193,
    name: "Hezekiah University, Umudi",
    type: "private",
    state: "Imo",
    website: "https://hezekiah.edu.ng/",
  },
  {
    id: 194,
    name: "Hillside University of Science and Technology, Okemisi, Ekiti State",
    type: "private",
    state: "Ekiti",
    website: "https://hust.edu.ng/",
  },
  {
    id: 195,
    name: "Huda University, Gusau, Zamafara State",
    type: "private",
    state: "Zamfara",
    website: "https://hug.edu.ng/",
  },
  {
    id: 196,
    name: "Iconic Open University, Sokoto State",
    type: "private",
    state: "Sokoto",
    website: "https://www.iconicuniversity.edu.ng/",
  },
  {
    id: 197,
    name: "Igbinedion University Okada",
    type: "private",
    state: "Edo",
    established: 1999,
    website: "https://www.iuokada.edu.ng",
  },
  {
    id: 198,
    name: "James Hope University, Lagos, Lagos State",
    type: "private",
    state: "Lagos",
    website: "https://jhu.edu.ng/",
  },
  {
    id: 199,
    name: "Jewel University, Gombe State",
    type: "private",
    state: "Gombe",
    website: "https://jeweluniversity.edu.ng/",
  },
  {
    id: 200,
    name: "Joseph Ayo Babalola University, Ikeji-Arakeji",
    type: "private",
    state: "Osun",
    established: 2006,
    website: "https://www.jabu.edu.ng",
  },
  {
    id: 201,
    name: "Karl-Kumm University, Vom, Plateau State",
    type: "private",
    state: "Plateau",
  },
  {
    id: 202,
    name: "Khadija University, Majia, Jigawa State",
    type: "private",
    state: "Jigawa",
    website: "https://kum.edu.ng/",
  },
  {
    id: 203,
    name: "Khalifa Isiyaku Rabiu University, Kano",
    type: "private",
    state: "Kano",
    website: "https://khairun.edu.ng/",
  },
  {
    id: 204,
    name: "Kings University, Ode Omu",
    type: "private",
    state: "Osun",
    established: 2009,
    website: "https://www.kingsuniversity.edu.ng/",
  },
  {
    id: 205,
    name: "Kola Daisi University Ibadan, Oyo State",
    type: "private",
    state: "Oyo",
    website: "https://www.koladaisiuniversity.edu.ng/",
  },
  {
    id: 206,
    name: "Kwararafa University, Wukari",
    type: "private",
    state: "Taraba",
    established: 2005,
    website: "https://www.kuw.edu.ng",
  },
  {
    id: 207,
    name: "Landmark University, Omu-Aran",
    type: "private",
    state: "Kwara",
    established: 2011,
    website: "https://www.lmu.edu.ng",
  },
  {
    id: 208,
    name: "Lead City University, Ibadan",
    type: "private",
    state: "Oyo",
    established: 2005,
    website: "https://www.lcu.edu.ng",
  },
  {
    id: 209,
    name: "Legacy University, Okija Anambra State",
    type: "private",
    state: "Anambra",
    website: "https://www.legacyuniversity.edu.ng/",
  },
  {
    id: 210,
    name: "Lighthouse University, Evbobanosa, Edo State",
    type: "private",
    state: "Edo",
  },
  {
    id: 211,
    name: "Lux Mundi University Umuahia, Abia State",
    type: "private",
    state: "Abia",
    website: "https://luxmundi.edu.ng/",
  },
  {
    id: 212,
    name: "Madonna University, Okija",
    type: "private",
    state: "Anambra",
    established: 1999,
    website: "https://www.madonnauniversity.edu.ng",
  },
  {
    id: 213,
    name: "Maduka University, Ekwegbe, Enugu State",
    type: "private",
    state: "Enugu",
    website: "https://madukauniversity.edu.ng/",
  },
  {
    id: 214,
    name: "Maranathan University, Mgbidi, Imo State",
    type: "private",
    state: "Imo",
    website: "https://maranathauniversitylagos.edu.ng/",
  },
  {
    id: 215,
    name: "Margaret Lawrence University, Umunede, Delta State",
    type: "private",
    state: "Delta",
    website: "https://mlugalilee.edu.ng/",
  },
  {
    id: 216,
    name: "Maryam Abacha American University of Nigeria, Kano State",
    type: "private",
    state: "Kano",
    website: "https://www.maaun.edu.ng/",
  },
  {
    id: 217,
    name: "Mcpherson University, Seriki Sotayo, Ajebo",
    type: "private",
    state: "Ogun",
    established: 2012,
    website: "https://www.mcu.edu.ng",
  },
  {
    id: 218,
    name: "Mercy Medical University, Iwo, Ogun State",
    type: "private",
    state: "Ogun",
    website: "https://mercymedicaluniversity.edu.ng/",
  },
  {
    id: 219,
    name: "Mewar International University, Masaka, Nasarawa State",
    type: "private",
    state: "Nasarawa",
    website: "https://www.miu.edu.ng/",
  },
  {
    id: 220,
    name: "Micheal & Cecilia Ibru University",
    type: "private",
    state: "Delta",
    established: 2015,
    website: "https://mciu.edu.ng/",
  },
  {
    id: 221,
    name: "Miva Open University, Abuja FCT",
    type: "private",
    state: "Abuja",
    website: "https://miva.university/",
  },
  {
    id: 222,
    name: "Mountain Top University",
    type: "private",
    state: "Ogun",
    established: 2005,
    website: "https://www.mtu.edu.ng",
  },
  {
    id: 223,
    name: "Mudiame University, Irrua, Edo State",
    type: "private",
    state: "Edo",
    website: "https://www.mudiameuniversity.edu.ng/",
  },
  {
    id: 224,
    name: "Muhammad Kamalud University Kwara",
    type: "private",
    state: "Kwara",
    website: "https://mku.edu.ng/",
  },
  {
    id: 225,
    name: "Newgate University, Minna, Niger State",
    type: "private",
    state: "Niger",
    website: "https://newgateuniversityminna.edu.ng/",
  },
  {
    id: 226,
    name: "Nigerian British University, Asa, Abia State",
    type: "private",
    state: "Abia",
    website: "https://nbu.edu.ng/",
  },
  {
    id: 227,
    name: "Nigerian University of Technology and Management, Apapa, Lagos State",
    type: "private",
    state: "Lagos",
    website: "https://nutm.edu.ng/",
  },
  {
    id: 228,
    name: "Nile University of Nigeria, Abuja",
    type: "private",
    state: "Abuja",
    established: 2009,
    website: "https://www.nileuniversity.edu.ng/",
  },
  {
    id: 229,
    name: "NOK University, Kachia, Kaduna State",
    type: "private",
    state: "Kaduna",
  },
  {
    id: 230,
    name: "North Eastern University, Gombe",
    type: "private",
    state: "Gombe",
    website: "https://pru.edu.ng/",
  },
  {
    id: 231,
    name: "NorthWest University Sokoto State",
    type: "private",
    state: "Sokoto",
    website: "https://nwus.edu.ng/",
  },
  {
    id: 232,
    name: "Novena University, Ogume",
    type: "private",
    state: "Delta",
    established: 2005,
    website: "https://www.novenauniversity.edu.ng",
  },
  {
    id: 233,
    name: "Obong University, Obong Ntak",
    type: "private",
    state: "Akwa Ibom",
    established: 2007,
    website: "https://www.obonguniversity.net",
  },
  {
    id: 234,
    name: "Oduduwa University, Ipetumodu - Osun State",
    type: "private",
    state: "Osun",
    established: 2009,
    website: "https://www.oduduwauniversity.edu.ng",
  },
  {
    id: 235,
    name: "Ojaja University Eiyenkorin, Kwara State",
    type: "private",
    state: "Kwara",
    website: "https://www.crownhilluniversity.edu.ng/",
  },
  {
    id: 236,
    name: "PAMO University of Medical Sciences, Port Harcourt",
    type: "private",
    state: "Rivers",
    established: 2012,
    website: "https://www.pums.edu.ng",
  },
  {
    id: 237,
    name: "Pan-Atlantic University, Lagos",
    type: "private",
    state: "Lagos",
    established: 2002,
    website: "https://www.pau.edu.ng",
  },
  {
    id: 238,
    name: "Paul University, Awka - Anambra State",
    type: "private",
    state: "Anambra",
    established: 2009,
    website: "https://www.pauluniversity.edu.ng",
  },
  {
    id: 239,
    name: "PeaceLand University, Enugu State",
    type: "private",
    state: "Enugu",
    website: "https://peacelanduni.edu.ng/",
  },
  {
    id: 240,
    name: "Peter University, Achina-Onneh Anambra State",
    type: "private",
    state: "Anambra",
    website: "https://puni.edu.ng/",
  },
  {
    id: 241,
    name: "Philomath University, Kuje, Abuja",
    type: "private",
    state: "Abuja",
    website: "https://www.philomath.edu.ng/",
  },
  {
    id: 242,
    name: "Phoenix University, Agwada, Nasarawa State",
    type: "private",
    state: "Nasarawa",
    website: "https://phoenixuniversity.edu.ng/",
  },
  {
    id: 243,
    name: "Precious Cornerstone University, Oyo",
    type: "private",
    state: "Oyo",
    established: 2005,
    website: "https://www.pcu.edu.ng",
  },
  {
    id: 244,
    name: "Prime University, Kuje, FCT Abuja",
    type: "private",
    state: "Abuja",
    website: "https://primeuniversity.edu.ng/",
  },
  {
    id: 245,
    name: "Rayhaan University, Kebbi",
    type: "private",
    state: "Kebbi",
    website: "https://rayhaanuniv.edu.ng/",
  },
  {
    id: 246,
    name: "Redeemer's University, Ede",
    type: "private",
    state: "Osun",
    established: 2005,
    website: "https://www.run.edu.ng",
  },
  {
    id: 247,
    name: "Renaissance University, Enugu",
    type: "private",
    state: "Enugu",
    established: 2005,
    website: "https://www.rnu.edu.ng",
  },
  {
    id: 248,
    name: "Rhema University, Obeama-Asa - Rivers State",
    type: "private",
    state: "Rivers",
    established: 2009,
    website: "https://www.rhemauniversity.edu.ng",
  },
  {
    id: 249,
    name: "Ritman University, Ikot Ekpene, Akwa Ibom",
    type: "private",
    state: "Akwa Ibom",
    established: 2015,
    website: "https://www.ritmanuniversity.edu.ng",
  },
  {
    id: 250,
    name: "Saisa University of Medical Sciences and Technology, Sokoto State",
    type: "private",
    state: "Sokoto",
    website: "https://saisa.edu.ng/",
  },
  {
    id: 251,
    name: "Salem University, Lokoja",
    type: "private",
    state: "Kogi",
    established: 2007,
    website: "https://www.salemuniversity.edu.ng",
  },
  {
    id: 252,
    name: "Sam Maris University, Ondo",
    type: "private",
    state: "Ondo",
    website: "https://sammarisuniversity.edu.ng/",
  },
  {
    id: 253,
    name: "Shanahan University Onitsha, Anambra State",
    type: "private",
    state: "Anambra",
    website: "https://shanahanuni.edu.ng/",
  },
  {
    id: 254,
    name: "Skyline University, Kano",
    type: "private",
    state: "Kano",
    established: 2013,
    website: "https://www.sun.edu.ng",
  },
  {
    id: 255,
    name: "Southwestern University, Oku Owa",
    type: "private",
    state: "Ogun",
    established: 2012,
    website: "https://www.southwesternuniversity.edu.ng",
  },
  {
    id: 256,
    name: "Spiritan University, Nneochi Abia State",
    type: "private",
    state: "Abia",
    website: "https://www.spiritanuniversity.edu.ng",
  },
  {
    id: 257,
    name: "Sports University, Idumuje, Ugboko, Delta State",
    type: "private",
    state: "Delta",
    website: "https://www.sportsuniversity.edu.ng/",
  },
  {
    id: 258,
    name: "Summit University, Offa",
    type: "private",
    state: "Kwara",
    established: 2015,
    website: "https://www.summituniversity.edu.ng",
  },
  {
    id: 259,
    name: "Tansian University, Umunya",
    type: "private",
    state: "Anambra",
    established: 2007,
    website: "https://tansianuniversity.edu.ng/",
  },
  {
    id: 260,
    name: "The Duke Medical University, Calabar, Cross River State",
    type: "private",
    state: "Cross River",
  },
  {
    id: 261,
    name: "Thomas Adewumi University, Oko-Irese, Kwara State",
    type: "private",
    state: "Kwara",
    website: "https://www.tau.edu.ng/",
  },
  {
    id: 262,
    name: "Topfaith University, Mkpatak, Akwa Ibom State",
    type: "private",
    state: "Akwa Ibom",
    website: "https://topfaith.edu.ng/",
  },
  {
    id: 263,
    name: "Trinity University Ogun State",
    type: "private",
    state: "Ogun",
    website: "https://www.trinityuniversity.edu.ng/",
  },
  {
    id: 264,
    name: "University of Mkar, Mkar",
    type: "private",
    state: "Benue",
    established: 2005,
    website: "https://umm.edu.ng/",
  },
  {
    id: 265,
    name: "University of Offa, Kwara State",
    type: "private",
    state: "Kwara",
    website: "https://unioffa.edu.ng/",
  },
  {
    id: 266,
    name: "University on the Niger, Umunya, Anambra State",
    type: "private",
    state: "Anambra",
    established: 2015,
    website: "https://uniniger.edu.ng/",
  },
  {
    id: 267,
    name: "Venite University, Iloro-Ekiti, Ekiti State",
    type: "private",
    state: "Ekiti",
    website: "https://veniteuniversity.edu.ng/",
  },
  {
    id: 268,
    name: "Veritas University, Abuja",
    type: "private",
    state: "Abuja",
    established: 2007,
    website: "https://www.veritas.edu.ng",
  },
  {
    id: 269,
    name: "Vision University, Ikogbo, Ogun State",
    type: "private",
    state: "Ogun",
    website: "https://visionuniversity.edu.ng/",
  },
  {
    id: 270,
    name: "Wellspring University, Evbuobanosa - Edo State",
    type: "private",
    state: "Edo",
    established: 2009,
    website: "https://www.wellspringuniversity.net",
  },
  {
    id: 271,
    name: "Wesley University Ondo",
    type: "private",
    state: "Ondo",
    established: 2007,
    website: "https://www.wesleyuni.edu.ng",
  },
  {
    id: 272,
    name: "West Midlands Open University, Ibadan, Oyo State",
    type: "private",
    state: "Oyo",
    website: "https://westmidlands.university/",
  },
  {
    id: 273,
    name: "Western Delta University, Oghara Delta State",
    type: "private",
    state: "Delta",
    website: "https://wdu.edu.ng",
  },
  {
    id: 274,
    name: "Westland University Iwo, Osun State",
    type: "private",
    state: "Osun",
    website: "https://westland.edu.ng/",
  },
  {
    id: 275,
    name: "Wigwe University, Isiokpo Rivers State",
    type: "private",
    state: "Rivers",
    website: "https://www.wigweuniversity.edu.ng/",
  },
]

export function getUniversitiesByType(type: University["type"]): University[] {
  return universities.filter((uni) => uni.type === type)
}

export function searchUniversities(query: string): University[] {
  const searchTerm = query.toLowerCase()
  return universities.filter(
    (uni) =>
      uni.name.toLowerCase().includes(searchTerm) ||
      uni.state.toLowerCase().includes(searchTerm) ||
      uni.abbreviation?.toLowerCase().includes(searchTerm),
  )
}

export function getUniversityById(id: number): University | undefined {
  return universities.find((uni) => uni.id === id)
}

export function getUniversitiesByState(state: string): University[] {
  return universities.filter((uni) => uni.state.toLowerCase() === state.toLowerCase())
}

export function getUniversityStats() {
  const federal = universities.filter((uni) => uni.type === "federal").length
  const state = universities.filter((uni) => uni.type === "state").length
  const private_unis = universities.filter((uni) => uni.type === "private").length

  return {
    total: universities.length,
    federal,
    state,
    private: private_unis,
  }
}

export { universities as nigerianUniversities }
